name: Validation

on:
  pull_request:
    branches:
      - main
  merge_group:
    types: [checks_requested]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Knip
        run: pnpm knip
